database:
  hostname: "dbserver"
  schema: "funny"
  username: "killedthis"
  password: "password"
contentGenerator:
  tmdbEnabled: false
  outputDirectory: "../../outputs"
  formatSiteFile: "%s.killedthis.top.html"
tmdb:
  apikey: "abcdefgh"